### PR TITLE
fix: rerender using new-conda-smithy

### PR DESCRIPTION
**Pull request by nichmor**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by baszalmstra** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
@conda-forge-admin, please rerender

One more time pls!

**Comment by wolfv** [comment]
@baszalmstra should `.dll` files go into `bin/` or `lib/`? This package currently installs both  dll and lib into `lib/`.

**Comment by wolfv** [comment]
This should be iiiit

**Pull request merged**
